import json
import time
import os
import math
import tldextract
import numpy as np
from collections import Counter
from sklearn.tree import DecisionTreeClassifier

# ==========================================
# PART 1: FEATURE EXTRACTION
# ==========================================
def calculate_entropy(domain_string):
    if not domain_string:
        return 0.0
    entropy = 0
    length = len(domain_string)
    character_counts = Counter(domain_string)
    for count in character_counts.values():
        p_x = count / length
        entropy += - p_x * math.log2(p_x)
    return round(entropy, 3)

def extract_features(fqdn):
    """Extract [Length, Entropy Score] from the fully qualified domain name (FQDN)"""
    require = tldextract.extract(fqdn)
    subdomain = require.subdomain
    
    # If there is no subdomain, treat it as safe (Entropy = 0)
    if not subdomain:
        return 0, 0.0
        
    return len(subdomain), calculate_entropy(subdomain)

# ==========================================
# PART 2: MACHINE LEARNING TRAINING (ID3)
# ==========================================
def train_ai_model():
    print("[*] Initializing and training the Decision Tree (ID3) model...")
    
    # Mock dataset. In a real scenario, load this from a CSV file generated by the Lab.
    # [Column 1: Length, Column 2: Entropy]
    X_train = np.array([
        [0, 0.0], [3, 1.5], [10, 2.1], [5, 1.8], [12, 2.5], # Label 0: Clean Traffic (Normal web browsing)
        [25, 4.2], [30, 4.5], [40, 4.8], [55, 4.9], [18, 4.1]  # Label 1: Malicious Traffic (DNScat2)
    ])
    
    # Corresponding labels: 0 = SAFE, 1 = MALWARE
    y_train = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

    # Initialize Decision Tree algorithm with 'entropy' criterion (ID3/C4.5 algorithm)
    model = DecisionTreeClassifier(criterion="entropy", max_depth=3)
    model.fit(X_train, y_train)
    
    print("[+] Training successful! Ready to protect the system.\n" + "="*50)
    return model

# ==========================================
# PART 3: ACTIVE RESPONSE
# ==========================================
def block_attacker_ip(ip_address):
    print(f"\n[!!!] ACTIVE RESPONSE TRIGGERED [!!!]")
    print(f"[*] Executing iptables to block IP: {ip_address}")
    
    # System command to cut off network connection of the IP showing data exfiltration signs
    os(f"sudo iptables -A FORWARD -s {ip_address} -j DROP")
    print(f"[+] Successfully isolated IP: {ip_address}\n")

# ==========================================
# PART 4: REAL-TIME DPI ENGINE
# ==========================================
def monitor_suricata_logs(log_path, ai_model):
    print(f"[*] Listening to Suricata data stream: {log_path} ...")
    
    try:
        with open(log_path, 'r') as f:
            # Move the pointer to the end of the file (similar to 'tail -f' command)
            f.seek(0, os.SEEK_END)
            
            while True:
                line = f.readline()
                if not line:
                    time.sleep(0.1) # Sleep for 0.1s if there is no new log
                    continue
                
                try:
                    # Parse the JSON log line from Suricata
                    log_data = json.loads(line)
                    
                    # Only care about DNS protocol packets
                    if log_data.get("event_type") == "dns":
                        dns_info = log_data.get("dns", {})
                        query_type = dns_info.get("type")
                        
                        # Only consider domain queries (e.g., A record, TXT, CNAME)
                        if query_type in ["query", "answer"]:
                            domain_queried = dns_info.get("rrname", "")
                            src_ip = log_data.get("src_ip", "")
                            
                            # 1. Feature Extraction
                            length, entropy = extract_features(domain_queried)
                            
                            # Skip very short domains to optimize performance
                            if length < 5:
                                continue
                                
                            # 2. Feed to AI for prediction
                            features = np.array([[length, entropy]])
                            prediction = ai_model.predict(features)[0] # Returns 0 or 1
                            
                            # 3. Decision Making
                            if prediction == 1:
                                print(f"[MALWARE ALERT] DNS Tunneling Detected!")
                                print(f"   -> Source IP: {src_ip}")
                                print(f"   -> Domain: {domain_queried}")
                                print(f"   -> Metrics: Length={length}, Entropy={entropy}")
                                
                                # Block IP immediately
                                block_attacker_ip(src_ip)
                            else:
                                # Uncomment the line below to print clean traffic to the screen
                                # print(f"[SAFE] {domain_queried} (Ent: {entropy})")
                                pass

                except json.JSONDecodeError:
                    continue # Skip if the log line has formatting errors

    except KeyboardInterrupt:
        print("\n[*] DPI monitoring system terminated.")
    except FileNotFoundError:
        print(f"[!] Error: Log file not found at {log_path}")
        print("[!] Ensure Suricata is running and generating the eve.json file")

# ==========================================
# MAIN FUNCTION
# ==========================================
if __name__ == "__main__":
    # Install required libraries: pip install scikit-learn numpy tldextract
    
    # 1. Initialize the "Brain" (AI Model)
    model = train_ai_model()
    
    # 2. Enable the "Eyes" (Point to Suricata's log file)
    # Note: Adjust this path to match your Ubuntu Server environment
    suricata_log_file = "/var/log/suricata/eve.json" 
    
    # 3. Run the system
    monitor_suricata_logs(suricata_log_file, model)